[theme.custom]
panel_bg    = "#1f2335"
surface0    = "#24283b"
surface1    = "#3b4261"
surface_dim = "#1f2335"
overlay0    = "#565f89"
overlay1    = "#737aa2"
text        = "#c0caf5"
subtext0    = "#a9b1d6"
mauve       = "#bb9af7"
green       = "#9ece6a"
yellow      = "#e0af68"
red         = "#f7768e"
blue        = "#7aa2f7"
teal        = "#73daca"
peach       = "#ff9e64"
