# Tokyo Night Storm
set -g status-style "fg=#c0caf5,bg=#24283b"
set -g status-left "#[fg=#7aa2f7,bg=#24283b,bold] #S #[default]"
set -g status-right "#[fg=#9ece6a,bg=#24283b] %Y-%m-%d #[fg=#e0af68,bg=#24283b] %H:%M #[default]"
setw -g window-status-current-format "#[fg=#24283b,bg=#7aa2f7,bold] #I:#W #[default]"
setw -g window-status-format "#[fg=#a9b1d6,bg=#292e42] #I:#W #[default]"
