# Rose Pine Dawn
set -g status-style "fg=#575279,bg=#faf4ed"
set -g status-left "#[fg=#286983,bg=#faf4ed,bold] #S #[default]"
set -g status-right "#[fg=#56949f,bg=#faf4ed] %Y-%m-%d #[fg=#ea9d34,bg=#faf4ed] %H:%M #[default]"
setw -g window-status-current-format "#[fg=#faf4ed,bg=#286983,bold] #I:#W #[default]"
setw -g window-status-format "#[fg=#797593,bg=#dfdad9] #I:#W #[default]"
